'use client';
import {useState} from 'react';import ReportingWidget from '@/components/ReportingWidget';import {Bell,FileText,MapPin,Clock3,ArrowRight,ShieldCheck} from 'lucide-react';
const reports=[{id:'INC-1042',type:'Medical',status:'RESPONDING',place:'Block C · Ground Floor',time:'2 min ago'},{id:'INC-1038',type:'Unsafe Location',status:'RESOLVED',place:'North Gate',time:'Today'}];
export default function Page(){const [tab,setTab]=useState<'report'|'reports'|'alerts'>('report');return <main className="min-h-screen">
 <header className="bg-slate-950 text-white"><div className="max-w-6xl mx-auto px-5 py-5 flex items-center justify-between"><div><div className="font-black tracking-[.18em]">MATRIX</div><div className="text-[10px] text-slate-400">EMERGENCY REPORTING ENGINE · SDK DEMO</div></div><div className="text-xs text-emerald-400 flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-emerald-400"/> SYSTEM READY</div></div></header>
 <div className="max-w-6xl mx-auto px-5 py-8"><div className="grid lg:grid-cols-[1fr_360px] gap-8 items-start"><section><div className="flex gap-2 mb-5"><button onClick={()=>setTab('report')} className={`px-4 py-2 rounded-xl text-xs font-black ${tab==='report'?'bg-slate-950 text-white':'bg-white border'}`}>Report</button><button onClick={()=>setTab('reports')} className={`px-4 py-2 rounded-xl text-xs font-black ${tab==='reports'?'bg-slate-950 text-white':'bg-white border'}`}>My Reports</button><button onClick={()=>setTab('alerts')} className={`px-4 py-2 rounded-xl text-xs font-black ${tab==='alerts'?'bg-slate-950 text-white':'bg-white border'}`}>Alerts</button></div>
 {tab==='report'?<ReportingWidget/>:tab==='reports'?<div className="space-y-3">{reports.map(r=><div key={r.id} className="bg-white border rounded-2xl p-5 flex gap-4 items-center"><div className="rounded-xl bg-red-50 p-3 text-red-600"><FileText/></div><div className="flex-1"><b>{r.id} · {r.type}</b><div className="text-xs text-slate-500 mt-1">{r.place} · {r.time}</div></div><span className="text-[10px] font-black px-2 py-1 rounded bg-blue-50 text-blue-700">{r.status}</span></div>)}</div>:<div className="bg-white border rounded-2xl p-6"><div className="flex items-center gap-3"><Bell className="text-amber-500"/><b>Incoming campus alerts</b></div><div className="mt-5 rounded-xl bg-red-50 border border-red-100 p-4"><b className="text-red-700">FIRE ALERT · BLOCK C</b><p className="text-xs text-red-700/70 mt-1">Avoid the 2nd floor. Emergency teams are responding.</p></div></div>}</section>
 <aside className="space-y-3"><div className="bg-white border rounded-2xl p-5"><div className="text-xs font-black text-slate-400">WHY THIS MODULE SELLS</div><h3 className="font-black text-lg mt-1">Embed emergency response into any campus app.</h3><p className="text-xs text-slate-500 mt-2">REST API + React widget + AI priority + anonymous reporting.</p><div className="mt-5 space-y-3 text-xs"><div className="flex gap-2"><MapPin size={15} className="text-blue-600"/> GPS + building context</div><div className="flex gap-2"><Clock3 size={15} className="text-blue-600"/> Real-time status pipeline</div><div className="flex gap-2"><ShieldCheck size={15} className="text-blue-600"/> Separation of identity from incident</div></div></div><div className="bg-slate-950 text-white rounded-2xl p-5"><div className="text-xs text-slate-400">MARKETPLACE ASSET</div><div className="text-2xl font-black mt-1">₹1.5–2 Cr</div><div className="text-xs text-slate-400">FED Coins · suggested positioning</div><div className="mt-4 text-xs flex items-center gap-2 text-emerald-300">Integration target &lt; 15 min <ArrowRight size={14}/></div></div></aside></div></div>
 </main>}
