'use client';
import {useState} from 'react'; import {motion} from 'framer-motion'; import {MapPin,Paperclip,ShieldCheck,Send,ChevronRight} from 'lucide-react';
const cats=[['MEDICAL','Medical'],['FIRE','Fire'],['HARASSMENT','Harassment'],['UNSAFE_LOCATION','Unsafe Location'],['INFRASTRUCTURE_FAILURE','Infrastructure Failure'],['ACCIDENT','Accident'],['OTHER','Other']];
export default function ReportingWidget(){
 const [category,setCategory]=useState('MEDICAL'),[desc,setDesc]=useState(''),[anon,setAnon]=useState(false),[loc,setLoc]=useState(true),[file,setFile]=useState<File|null>(null),[result,setResult]=useState<any>(null),[loading,setLoading]=useState(false);
 async function submit(){setLoading(true);let evidenceUrl:string|undefined; if(file){const fd=new FormData();fd.append('file',file);const up=await fetch('/api/v1/upload',{method:'POST',body:fd});if(up.ok)evidenceUrl=(await up.json()).url;} let latitude=20.3524,longitude=85.8185;try{if(navigator.geolocation)await new Promise<void>(r=>navigator.geolocation.getCurrentPosition(p=>{latitude=p.coords.latitude;longitude=p.coords.longitude;r()},()=>r(),{timeout:1500}))}catch{};const res=await fetch('/api/v1/incidents',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({category,description:desc||'Emergency reported by student',anonymous:anon,reporterName:'Student',latitude:loc?latitude:undefined,longitude:loc?longitude:undefined,building:'Block C',evidenceUrl})});const json=await res.json();setResult(json);setLoading(false)}
 if(result?.data)return <div className="rounded-3xl bg-slate-950 text-white p-7 shadow-2xl"><div className="text-emerald-400 text-sm font-bold">INCIDENT CREATED</div><div className="mt-2 text-4xl font-black">{result.incidentId}</div><div className="mt-5 rounded-2xl bg-white/10 p-4"><div className="text-xs text-slate-400">AI PRIORITY</div><div className="mt-1 text-2xl font-black">{result.priority.severity}</div><div className="mt-2 text-sm text-slate-300">{result.priority.reason}</div></div><div className="mt-5 flex items-center gap-2 text-sm text-slate-300"><ShieldCheck size={17}/>Your report is in the response pipeline.</div></div>;
 return <motion.div initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} className="rounded-3xl bg-white border border-slate-200 shadow-xl p-6">
  <div className="flex items-center justify-between"><div><div className="text-xs font-black tracking-[.18em] text-red-600">MATRIX REPORTING ENGINE</div><h2 className="text-2xl font-black mt-1">Report an emergency</h2></div><div className="rounded-xl bg-red-50 p-3 text-red-600"><ShieldCheck/></div></div>
  <button onClick={()=>setCategory('MEDICAL')} className="w-full mt-6 rounded-3xl bg-red-600 hover:bg-red-700 text-white py-6 shadow-lg shadow-red-200"><div className="text-4xl">🆘</div><div className="mt-1 font-black text-xl">GET HELP NOW</div><div className="text-xs opacity-80">Location + priority captured automatically</div></button>
  <div className="mt-6 grid grid-cols-2 sm:grid-cols-3 gap-2">{cats.map(([v,l])=><button key={v} onClick={()=>setCategory(v)} className={`rounded-xl border p-3 text-left text-xs font-bold ${category===v?'border-red-500 bg-red-50 text-red-700':'border-slate-200 hover:bg-slate-50'}`}>{l}</button>)}</div>
  <textarea value={desc} onChange={e=>setDesc(e.target.value)} className="mt-5 w-full min-h-24 rounded-xl border border-slate-200 p-3 text-sm outline-none focus:ring-2 focus:ring-red-100" placeholder="What happened? Add the most useful detail you can."/>
  <div className="mt-3 grid sm:grid-cols-2 gap-2"><label className="rounded-xl border border-slate-200 p-3 flex gap-2 items-center text-xs font-bold cursor-pointer"><Paperclip size={15}/> {file?file.name:"Add photo / video"}<input type="file" accept="image/*,video/*" className="hidden" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><button onClick={()=>setLoc(!loc)} className={`rounded-xl border p-3 flex gap-2 items-center text-xs font-bold ${loc?'border-blue-300 bg-blue-50 text-blue-700':'border-slate-200'}`}><MapPin size={15}/> {loc?'Location attached':'Attach location'}</button></div>
  <label className="mt-4 flex items-center gap-3 rounded-xl bg-slate-50 p-3 text-xs"><input type="checkbox" checked={anon} onChange={e=>setAnon(e.target.checked)}/><span><b>Anonymous report</b><br/><span className="text-slate-500">Identity is not stored with incident data.</span></span></label>
  <button disabled={loading} onClick={submit} className="mt-5 w-full rounded-xl bg-slate-950 text-white py-3 font-black flex items-center justify-center gap-2 disabled:opacity-50">{loading?'Prioritizing…':<>Submit emergency <Send size={16}/></>}</button>
 </div>
}
